apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sit
  name: nlpapi-deployment
spec:
  selector:
    matchLabels:
      app: nlpapi-pod
  replicas: 1
  template:
    metadata:
      name: nlpapi
      labels:
        app: nlpapi-pod
    spec:
      containers:
      - name: nlpapi-container
        image: ubuntu/poc:nlp
        ports:
        - containerPort: 8090
