apiVersion: v1
kind: Service
metadata:
  namespace: uat
  name: nlpapi-service
spec:
  type: NodePort
  selector:
    app: nlpapi-pod
  ports:
    #外部訪問的port
    nodePort: 8090
    #內部訪問的port
    port: 8090
    #pod的port
    targetPort: 8090
